# Generated by Django 3.0.2 on 2020-02-29 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=20)),
                ('href', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=2000)),
                ('author', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Brand_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_href', models.CharField(default='', max_length=1000)),
                ('ajax_href', models.CharField(default='', max_length=1000)),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
                ('sub', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
            ],
            options={
                'db_table': 'brands_sub',
            },
        ),
    ]
