# Generated by Django 3.0.6 on 2020-05-30 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=20)),
                ('href', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='BrandForeign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=20)),
                ('href', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'brands_foreign',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=6000)),
                ('author', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField()),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(default='', max_length=1000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wordsMap',
            },
        ),
        migrations.CreateModel(
            name='Word_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner_flag', models.BooleanField(default=False)),
                ('ner', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Word')),
            ],
            options={
                'db_table': 'word_brands',
            },
        ),
        migrations.CreateModel(
            name='tagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(max_length=6000)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'tagger',
            },
        ),
        migrations.CreateModel(
            name='standpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standpoint', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'standpoint',
            },
        ),
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('happy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('good', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surprise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anger', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fear', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disgust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'sentiment',
            },
        ),
        migrations.CreateModel(
            name='NewsForeign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=2000)),
                ('author', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField()),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=1000)),
                ('is_headline', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.BrandForeign')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
            ],
            options={
                'db_table': 'news_foreign',
            },
        ),
        migrations.AddField(
            model_name='new',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject'),
        ),
        migrations.CreateModel(
            name='HotWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tally', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Word')),
            ],
            options={
                'db_table': 'hot_words',
            },
        ),
        migrations.CreateModel(
            name='Cluster_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cluster', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'cluster_day',
            },
        ),
        migrations.CreateModel(
            name='Brand_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_href', models.CharField(default='', max_length=1000)),
                ('ajax_href', models.CharField(default='', max_length=1000)),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
                ('sub', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
            ],
            options={
                'db_table': 'brands_sub',
            },
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'aspect',
            },
        ),
    ]
