# Generated by Django 3.0.2 on 2020-03-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wordsMap',
            },
        ),
        migrations.CreateModel(
            name='Word_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner_flag', models.BooleanField(default=False)),
                ('ner', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Word')),
            ],
            options={
                'db_table': 'word_brands',
            },
        ),
    ]
