# Generated by Django 3.0.2 on 2020-03-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0002_word_word_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tally', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Brand')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Subject')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.Word')),
            ],
            options={
                'db_table': 'hot_words',
            },
        ),
    ]
