# Generated by Django 3.0.3 on 2020-03-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0003_hotword'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='news',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
