# Generated by Django 3.0.2 on 2020-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0003_hotword'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
