# Generated by Django 3.0.3 on 2020-03-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0004_new_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='news',
            new_name='url',
        ),
    ]
