# Generated by Django 3.0.3 on 2020-03-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0005_auto_20200303_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
