# Generated by Django 3.0.3 on 2020-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0006_auto_20200303_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandForeign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=20)),
                ('href', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'brands_foreign',
            },
        ),
    ]
