# Generated by Django 3.0.2 on 2020-03-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0007_auto_20200305_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
