# Generated by Django 3.0.3 on 2020-03-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0008_newsforeign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsforeign',
            old_name='isHeadline',
            new_name='is_headline',
        ),
    ]
