# Generated by Django 3.0.3 on 2020-05-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0009_auto_20200311_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cluster', models.IntegerField()),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'cluster_day',
            },
        ),
    ]
