# Generated by Django 3.0.3 on 2020-05-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0010_cluster_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster_day',
            old_name='news_id',
            new_name='news',
        ),
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('happy', models.FloatField()),
                ('good', models.FloatField()),
                ('surprise', models.FloatField()),
                ('anger', models.FloatField()),
                ('sad', models.FloatField()),
                ('fear', models.FloatField()),
                ('disgust', models.FloatField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'sentiment',
            },
        ),
    ]
