# Generated by Django 3.0.3 on 2020-05-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0012_auto_20200524_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster_week_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_period', models.CharField(max_length=50)),
                ('brand', models.IntegerField()),
                ('cluster', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'cluster_week_brand',
            },
        ),
        migrations.CreateModel(
            name='cluster_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_period', models.CharField(max_length=50)),
                ('cluster', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdb.New')),
            ],
            options={
                'db_table': 'cluster_week',
            },
        ),
    ]
